### ISSUE TITLE
Frontend Routes, Backend routes and Schemas

### ISSUE THREAD

**Issue by carlosaicrag** [carlosaicrag/familiarize#8]
need to document what are front end routes, backend routes and schemas are going to look like in our wiki.

**Comment by carlosaicrag** [comment]
each one of those should have their own page on the wiki just like full stacks.

**Comment by JoeBumbaca** [comment]
Carlos, each of these have been written and a seperate wiki page created.  I'll leave the issue open until you review.  If you approve, you can close it.

**Comment by carlosaicrag** [comment]
I just added 1 extra route in the front end to show the users profile and one in the backend to grab the trees that we will display on the users show page

**Comment by carlosaicrag** [comment]
go ahead and close this issue once you've looked at those new routes I added

**Comment by JoeBumbaca** [comment]
just moved it to the users tree backend route to the tree section.  All Tree backend routes are complete, moving onto Nodes.
